name = "VirtualAcousticOcean"
uuid = "629e117c-1786-4222-ab4a-1acab234d923"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
UnderwaterAcoustics = "0efb1f7a-1ce7-46d2-9f48-546a4c8fbb99"

[compat]
julia = "1.6"
UnderwaterAcoustics = "0.3"
